# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CICD
on:
push:
    branches:
      - master
jobs:
test:
   name: Build and Test
   runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: Set up JDK 17
    uses: actions/setup-java@v2
    with:
      java-version: '17.0.*'
      distribution: 'temurin'
      cache: maven
  - name: test with Maven
    run: mvn test
deploy:
  name: Deploy to Heroku
  runs-on: ubuntu-latest
  needs: test
  steps:
    - uses: actions/checkout@v2
      # This is the action
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "superheroes" #Must be unique
                                        #in Heroku
        heroku_email: "email"
    
